<?php
  function shift_cipher_menu() {
    $items['shift_cipher'] = array(
      'title' => 'shift cipher',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('form_input'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    $items['shift_cipher_success_page'] = array(
      'title' => 'cipher result',
      'page callback' => 'result',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    return $items;
  }


//======================FORM INPUT =============================================
  function form_input() {
    $form['shift_value'] = array(
      '#title' => "shift value",
      '#type' => 'textfield',
      '#description' => t('Shift Value'),
      '#element_validate' => array('element_validate_integer_positive'),
      '#required' => TRUE,
    );
    $form['shift_direction'] = array(
      '#title' => "shift direction",
      '#type' => 'textfield',
      '#description' => t('Shift Left / Right'),
      '#element_validate' => array('element_validate_direction'),
      '#required' => TRUE,
    );
    $form['phrase'] = array(
      '#title' => "sentence to encrypt",
      '#type' => 'textfield',
      '#description' => t('Please enter the phraze you want to encrypt'),
      '#element_validate' => array('element_validate_phrase'),
      '#required' => TRUE,
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Encrypt',
    );
    return $form;
  }

  function form_input_submit($form, &$form_state) {
    $value = $form_state['values']['shift_value'];
    $direction = $form_state['values']['shift_direction'];
    $phrase = $form_state['values']['phrase'];
  }

  //======================ELEMENT VALIDATIONS=====================================
  function element_validate_direction($element) {
    $user_input_direction = strtolower($element['#value']);
    $acceptable_directions = array('left', 'right');
    if(!in_array($user_input_direction, $acceptable_directions)) {
      form_error($element, t('The direction needs to be either Left or Right.'));
    }
  }

  function element_validate_phrase($element) {
    $phrase_exploded = explode(" ", $element['#value']);
    foreach ($phrase_exploded as $word) {
      if(!ctype_alpha($word)) {
        form_error($element, t('The phrase needs to consist of all letters.'));
      }
    }
  }
